### ISSUE TITLE
Roadmap 2015

### ISSUE THREAD

**Issue by MrSaints** [ClaudeBot/ClaudeBot#2]
_Really, just a personal note that I do for every project I plan to continue for a while._

The list of items below are ALL under consideration. They may or may not be added / completed.
## Project
- [ ] Readme.md: use tables; needs complete rewriting
- [x] Persistence solution (PostgreSQL supported by Heroku or Redis?) -- decided to go with Redis 253d44c136fc17d33568fe767102069a5481a2e5
- [x] Autodeployment (via webhooks?) -- Travis CI and Github + Heroku hooks
## General
- [ ] Grunt / Gulp lint, build and test tasks (continuous integration via Travis)
- [ ] Reorganisation: set up an organisation for the bot and relocate every custom script into their own repository (to allow for contribution to hubot-scripts organisation and easier package management via NPM) -- WIP 9bee458b018ec67fbaa41357a911a30a7281b4e8
- [ ] ~~Switch to Hubot KeepAlive script~~
- [ ] Dashboard?
- [ ] Update script packages to match updated hubot-scripts package template
- [ ] Updated script dependencies (e.g. hubot-twitch is outdated)
- [ ] use strict and check for unused dependencies / vars; CoffeeLint?
## Features
- [x] Mail system -- 15c25106eed6c86fca0c787f3bbd95665f90afbd
- [x] Role-based command restrictions -- 2fb13c9aa816423fd1a5fcfc8fa24762ebc16cde
- [x] hitbox API -- 58bbef3dab599a0d2d3e4efc1cee65af0bea51ec
- [ ] Simpler note storage system to replace `remember.coffee`
- [ ] JSDelivr (possibly replace CDNJS)
- [ ] DuckDuckGo API (possibly replace Wikipedia command as DDG relies on it)
- [ ] Google Calendar / Trello reminders via cron?
- [x] Link shortener -- bfcd9a760f491436a07eb19df42075932821bebd
- [ ] hubot-longurl (filter for long URLs)
- [x] Archive.today -- https://github.com/ClaudeBot/hubot-archive-today
### External
- [x] Refactor `steam.coffee`'s persistence to match that of Mail.coffee -- 0b9515f09ef3b0f5e070549a1d0536f703f4a28a
- [ ] Refactor `hubot-steam-webapi` to use classes
- [ ] Add "shortcuts" / account linking for `hubot-steam-webapi`
- [x] Re-add `steam.coffee`'s persistence as it was removed in b64267ff01943a725b01374113489acd328d3884 -- Added https://github.com/ClaudeBot/hubot-steam-webapi/commit/43de8ec1bf4c36d489966754c30b2a887bc9a7a7
- [x] Statuses of followed channels on Twitch aka favourites -- 3fb8eaf2a0121b1ea91b9e20be6367b792a2da5a
- [x] Check followed channels that streamed only in the last 6 hours (https://github.com/justintv/Twitch-API/issues/249) -- partially implemented 25f89aee44b3a929939945cfa97116b76320c308
- [ ] Add quick W/L game summary for Dota 2 history command
- [ ] hitbox: ~~switch to /media endpoint for~~ better status detection (810e76eaf433037ade37151bc8728f8b537fd3d6) and error handling; and add more features
- [ ] Twitch and Hitbox notification via mail API (Mailgun)? A "notify me" command which sets the user and the target in an array. Perhaps poll every X minutes for live streamers?
- [ ] AB guessing game: add win messages
- [ ] AB guessing game: win streak / score
- [x] Store long messages in a paste online -- experimental implementation https://github.com/ClaudeBot/hubot-longtext/issues/1
- [x] help should respond with a link to the online help docs
- [x] Upgrade to YouTube API v3 (v2 deprecated)
### Local
- [ ] YouTube search should return 5 links, not a random video
- [ ] Replace use of MsgPack + base64 for good ol' JSON serialization
- [ ] Time-based mails
- [ ] Advance command restrictions: default in env variable; set per role and save in brain
- [ ] ~~Google search returns encoded URI links. Needs fixing~~
### Others
- [ ] Immutable.js

**Comment by MrSaints** [comment]
## Migration

- Forego (application manager): requires Go installed via Godeb
- Node installed via NVM
- CHMOD 755 bin/hubot

**Comment by Jaglag** [comment]
Add a rss feed

**Comment by MrSaints** [comment]
@Jaglag :sweat:

**Comment by Jaglag** [comment]
XD
